apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ .Values.gateway.name }}
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: {{ .Values.envoyProxy.replicas | default 2 }}
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: DoesNotExist
      envoyService:
        type: {{ .Values.envoyProxy.serviceType | default "NodePort" }}
        {{- if .Values.envoyProxy.nodePort }}
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
                - name: http
                  port: {{ .Values.gateway.port }}
                  protocol: TCP
                  targetPort: 8080
                  nodePort: {{ .Values.envoyProxy.nodePort }}
        {{- end }}
