apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  gatewayClassName: {{ .Values.gatewayClass.name }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.port }}

