description: Install kured for safe rolling node reboots
apiVersion: v2
appVersion: 2.15.1
version: 5.12.0
name: kured
type: application
dependencies:
- version: 5.12.0
  name: kured
  repository: https://kubereboot.github.io/charts


