dependencies:
- name: prometheus-node-exporter
  version: 4.56.3
  repository: https://prometheus-community.github.io/helm-charts
name: node-exporter
version: 4.56.3
appVersion: 1.12.1
type: application
apiVersion: v2


