apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-tool
  labels:
    spydersoft.io/category: cluster-tools
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            spydersoft.io/external-secrets: "true"
  template:
    metadata:
      name: "{{ nameNormalized }}-external-secrets"
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true
      labels:
        spydersoft.io/category: cluster-tools
    spec:
      project: cluster-tools
      source:
        repoURL: https://github.com/spydersoft-consulting/ops-argo
        targetRevision: main
        path: "cluster-tools/tools/external-secrets"
        helm: {}
      destination:
        server: "{{ server }}"
        namespace: "external-secrets"
      ignoreDifferences:
        - group: "*"
          kind: "*"
          managedFieldsManagers:
            - external-secrets
      # - group: '*'
      #   kind: '*'
      #   jqPathExpressions:
      #   - '.webhooks[]?.clientConfig.caBundle'
      #   - '.webhooks[]?.client'
      syncPolicy:
        # automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
        #   prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
        #   selfHeal: false
        syncOptions: # Sync options which modifies sync behavior
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
