apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: linkerd-crd-tool
  labels:
    spydersoft.io/category: cluster-tools
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            spydersoft.io/linkerd-crds: "true"
  template:
    metadata:
      name: "{{ nameNormalized }}-linkerd-crds"
      labels:
        spydersoft.io/category: cluster-tools
    spec:
      project: cluster-tools
      source:
        repoURL: https://github.com/spydersoft-consulting/ops-argo
        targetRevision: main
        path: "cluster-tools/tools/linkerd-crds"
        helm: {}
      destination:
        server: "{{ server }}"
        namespace: "linkerd"
      ignoreDifferences:
        - group: apiextensions.k8s.io
          name: serviceprofiles.linkerd.io
          kind: CustomResourceDefinition
          jsonPointers:
            - /spec/preserveUnknownFields
      syncPolicy:
        syncOptions: # Sync options which modifies sync behavior
          - CreateNamespace=true
          - ServerSideApply=true
