production_scrape_config:
  enabled: true
  name: production-scrape-config
kube-prometheus:
  prometheus:
    ingress:
      hostname: prod-cluster.mattgerega.net
    thanos:
      ingress:
        hostname: prod-cluster.mattgerega.net
    alertmanager:
      ingress:
        hostname: prod-cluster.mattgerega.net
    externalLabels:
      cluster: production
    additionalScrapeConfigs:
      enabled: true
      type: external
      external:
        name: production-scrape-config
        key: scrape-jobs.yaml