type: application
version: 0.37.0
dependencies:
- name: descheduler
  version: 0.37.0
  repository: https://kubernetes-sigs.github.io/descheduler/
apiVersion: v2
name: descheduler
appVersion: 0.36.0


