name: linkerd-control-plane
apiVersion: v2
type: application
version: 2026.1.3
dependencies:
- name: linkerd-control-plane
  version: 2026.1.3
  repository: https://helm.linkerd.io/edge
appVersion: edge-25.5.2


