name: linkerd-control-plane
type: application
version: 2026.5.3
apiVersion: v2
appVersion: edge-25.5.2
dependencies:
- name: linkerd-control-plane
  repository: https://helm.linkerd.io/edge
  version: 2026.5.3


