dependencies:
- name: linkerd-control-plane
  repository: https://helm.linkerd.io/edge
  version: 2025.7.5
version: 2025.7.5
type: application
name: linkerd-control-plane
appVersion: edge-25.5.2
apiVersion: v2


