version: 2025.7.6
dependencies:
- repository: https://helm.linkerd.io/edge
  name: linkerd-control-plane
  version: 2025.7.6
apiVersion: v2
name: linkerd-control-plane
type: application
appVersion: edge-25.5.2


