dependencies:
- version: 2025.10.3
  repository: https://helm.linkerd.io/edge
  name: linkerd-control-plane
type: application
apiVersion: v2
name: linkerd-control-plane
version: 2025.10.3
appVersion: edge-25.5.2


