apiVersion: v2
name: linkerd-control-plane
appVersion: edge-25.5.2
type: application
version: 2025.5.2
dependencies:
  - name: linkerd-control-plane
    version: 2025.5.2
    repository: https://helm.linkerd.io/edge
