dependencies:
- version: 2025.8.5
  name: linkerd-control-plane
  repository: https://helm.linkerd.io/edge
version: 2025.8.5
apiVersion: v2
appVersion: edge-25.5.2
type: application
name: linkerd-control-plane


