{{- if eq .Values.clusterName "nonproduction" }}
---
# ExternalSecret for linkerd-multicluster namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-credentials-internal-es
  namespace: linkerd-multicluster
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cluster-credentials-internal
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: mirror.linkerd.io/remote-kubeconfig
      data:
        kubeconfig: "{{`{{ .kubeconfig }}`}}"
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: secrets-k8/linkerd-multicluster/nonproduction-to-internal
        property: kubeconfig
        conversionStrategy: Default
        decodingStrategy: None
---
# ExternalSecret for linkerd namespace (with annotations/labels)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-credentials-internal-es
  namespace: linkerd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cluster-credentials-internal
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: mirror.linkerd.io/remote-kubeconfig
      metadata:
        annotations:
          multicluster.linkerd.io/cluster-domain: cluster.local
          multicluster.linkerd.io/trust-domain: cluster.local
        labels:
          multicluster.linkerd.io/cluster-name: internal
      data:
        kubeconfig: "{{`{{ .kubeconfig }}`}}"
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: secrets-k8/linkerd-multicluster/nonproduction-to-internal
        property: kubeconfig
        conversionStrategy: Default
        decodingStrategy: None
{{- end }}
