{{- if eq .Values.clusterName "nonproduction" }}
---
apiVersion: multicluster.linkerd.io/v1alpha3
kind: Link
metadata:
  annotations:
    linkerd.io/created-by: helm/gitops {{ .Chart.AppVersion }}
  name: internal
  namespace: linkerd-multicluster
spec:
  clusterCredentialsSecret: cluster-credentials-internal
  federatedServiceSelector:
    matchLabels:
      mirror.linkerd.io/federated: member
  gatewayAddress: tfx-internal.gerega.net:30143
  gatewayIdentity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local
  gatewayPort: "30143"
  probeSpec:
    path: /ready
    period: 3s
    port: "30191"
  remoteDiscoverySelector:
    matchLabels:
      mirror.linkerd.io/exported: remote-discovery
  selector:
    matchLabels:
      mirror.linkerd.io/exported: "true"
  targetClusterDomain: cluster.local
  targetClusterLinkerdNamespace: linkerd
  targetClusterName: internal
{{- end }}
