linkerd-viz:
  revisionHistoryLimit: 3
  # CPU requests based on observed `kubectl top pods -n linkerd-viz --containers`
  # usage across all 3 clusters (metrics-api ~1-5m, tap ~2-4m, tap-injector ~1m,
  # web ~1m).
  metricsAPI:
    resources:
      cpu:
        request: 2m
  dashboard:
    enforcedHostRegexp: .*
    resources:
      cpu:
        request: 1m
  tap:
    resources:
      cpu:
        request: 2m
    externalSecret: true
    caBundle: |
      -----BEGIN CERTIFICATE-----
      MIIBlTCCATqgAwIBAgIRALtrDsRnldb8/Fl48T48D4EwCgYIKoZIzj0EAwIwKDEm
      MCQGA1UEAxMdd2ViaG9vay5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjIwNjMw
      MTY1NDAzWhcNMjcwNjI5MTY1NDAzWjAoMSYwJAYDVQQDEx13ZWJob29rLmxpbmtl
      cmQuY2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEMGzw8o
      jkN9+agfCaXGvxBQ9zrTA9KjjrWKtjYnENE+DbcgtmFpRc0bLatGv1nsS1RX/Ge4
      DrTQnpMbHOCbVoejRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
      AgEBMB0GA1UdDgQWBBQnkBlvddok5ypt6IutQsur92W06zAKBggqhkjOPQQDAgNJ
      ADBGAiEAilyr2DmQ8MIRGaak2+pQnrmcg7SWljiDWIL/IFJmieACIQClCWFPRMQJ
      9DMD/KIJWeWLzCpDSMnBxr1Vn3iYHWvMdg==
      -----END CERTIFICATE-----
  tapInjector:
    resources:
      cpu:
        request: 1m
    externalSecret: true
    caBundle: |
      -----BEGIN CERTIFICATE-----
      MIIBlTCCATqgAwIBAgIRALtrDsRnldb8/Fl48T48D4EwCgYIKoZIzj0EAwIwKDEm
      MCQGA1UEAxMdd2ViaG9vay5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjIwNjMw
      MTY1NDAzWhcNMjcwNjI5MTY1NDAzWjAoMSYwJAYDVQQDEx13ZWJob29rLmxpbmtl
      cmQuY2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEMGzw8o
      jkN9+agfCaXGvxBQ9zrTA9KjjrWKtjYnENE+DbcgtmFpRc0bLatGv1nsS1RX/Ge4
      DrTQnpMbHOCbVoejRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
      AgEBMB0GA1UdDgQWBBQnkBlvddok5ypt6IutQsur92W06zAKBggqhkjOPQQDAgNJ
      ADBGAiEAilyr2DmQ8MIRGaak2+pQnrmcg7SWljiDWIL/IFJmieACIQClCWFPRMQJ
      9DMD/KIJWeWLzCpDSMnBxr1Vn3iYHWvMdg==
      -----END CERTIFICATE-----
  grafana:
    externalUrl: https://grafana.mattgerega.net/
  prometheus:
    enabled: false
  podAnnotations:
    linkerd.io/inject: enabled
    logs.spydersoft.io/collect: "true"
    logs.spydersoft.io/format: "logfmt"
