apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-application-sets
  labels:
    spydersoft.io/environment: internal
    spydersoft.io/category: app
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: applicationSets
    repoURL: https://github.com/spydersoft-consulting/ops-internal-cluster
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated:
      selfHeal: false #true
      prune: true
