configFile: ""

alloy:
  controller:
    revisionHistoryLimit: 3
    podAnnotations:
      linkerd.io/inject: enabled
      config.linkerd.io/opaque-ports: "4317,4318"
  alloy:
    extraPorts:
      - name: "otlp-grpc"
        port: 4317
        targetPort: 4317
        protocol: "TCP"
        appProtocol: "kubernetes.io/h2c"
      - name: "otlp-http"
        port: 4318
        targetPort: 4318
        protocol: "TCP"