dependencies:
- repository: https://helm.linkerd.io/edge
  name: linkerd-multicluster
  version: 2026.4.1
apiVersion: v2
name: linkerd-multicluster
type: application
appVersion: edge-26.1.4
version: 2026.4.1


