apiVersion: v2
appVersion: edge-26.1.4
dependencies:
- repository: https://helm.linkerd.io/edge
  version: 2026.3.2
  name: linkerd-multicluster
version: 2026.3.2
type: application
name: linkerd-multicluster


