version: 2026.1.4
type: application
dependencies:
- repository: https://helm.linkerd.io/edge
  version: 2026.1.4
  name: linkerd-multicluster
apiVersion: v2
appVersion: edge-26.1.4
name: linkerd-multicluster


