dependencies:
- repository: https://helm.linkerd.io/edge
  name: linkerd-multicluster
  version: 2026.1.2
name: linkerd-multicluster
appVersion: edge-25.12.2
version: 2026.1.2
apiVersion: v2
type: application


