apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: linkerd-trust-anchor-es

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: linkerd-trust-anchor
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      metadata:
        annotations:
          linkerd.io/created-by: linkerd/cli stable-2.11.0
        labels:
          linkerd.io/control-plane-component: identity
          linkerd.io/control-plane-ns: linkerd
      data:
        tls.crt: "{{ `{{ .cert }}` }}"
        tls.key: "{{ `{{ .certKey }}` }}"
  data:
  - secretKey: cert
    remoteRef:
      key: secrets-k8/linkerd
      property: cacrt
  - secretKey: certKey
    remoteRef:
      key: secrets-k8/linkerd
      property: caket