apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret-es

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        atlassian-api-token: "{{ .atlassian-api-token }}"
        atlassian-email: "{{ .atlassian-email }}"
  data:
    - secretKey: atlassian-api-token
      remoteRef:
        key: secrets-infra/atlassian/api
        property: token
    - secretKey: atlassian-email
      remoteRef:
        key: secrets-infra/atlassian/api
        property: email
