apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret-es

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        atlassian-api-token: "{{ .atlassian_api_token }}"
        atlassian-email: "{{ .atlassian_email }}"
  data:
    - secretKey: atlassian_api_token
      remoteRef:
        key: secrets-k8/atlassian/api
        property: token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: atlassian_email
      remoteRef:
        key: secrets-k8/atlassian/api
        property: email
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
