apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-azuread-secret-es

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argo-azuread-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        cert: "{{ .cert }}"
  data:
    - secretKey: cert
      remoteRef:
        key: secrets-k8/argo/azuread
        property: cert
