apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-oidc-client-es

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argo-oidc-creds
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        oidc.clientid: "{{ .clientid }}"
        oidc.clientsecret: "{{ .secret }}"
  data:
    - secretKey: clientid
      remoteRef:
        key: secrets-k8/argo/oidc
        property: clientid
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secret
      remoteRef:
        key: secrets-k8/argo/oidc
        property: clientsecret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
