apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-github-https-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argo-github-https-creds
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: https://github.com/spydersoft-consulting/
        password: "{{ .password }}"
        username: "{{ .username }}"
  data:
    - secretKey: username
      remoteRef:
        key: secrets-k8/github
        property: name
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: secrets-k8/github
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
